### ISSUE TITLE
Tested on raspberry pi 3. Runs ok minor fps drops

### ISSUE THREAD

**Issue by Askmewho** [pjasicek/OpenClaw#131]
https://youtu.be/oXyc1eKjsX4

Keep on it!

Thanks!

**Comment by symbios24** [comment]
hi any info about what files i put from the original game coz i tried the rez file and it says it needs an asset file also

**Comment by pjasicek** [comment]
> hi any info about what files i put from the original game coz i tried the rez file and it says it needs an asset file also

 <CustomArchive>ASSETS.ZIP</CustomArchive> option in config.xml corresponds to path of ASSETS.ZIP which is located in Build_Release folder in this repo

**Comment by symbios24** [comment]
yeah i see the files do i take them from here and put the in the build release folder for the game to work?

**Comment by pjasicek** [comment]
> yeah i see the files do i take them from here and put the in the build release folder for the game to work?
> or i take them from the original game?

If you want to run the game locally after compilation, then yes, you need to put the output binary to the Build_Release folder and run it from there.

**Comment by symbios24** [comment]
i did that and now i get an error saying:

some of the actor prototypes were not loaded

failed to initialize exiting

**Comment by pjasicek** [comment]
> i did that and now i get an error saying:
> 
> some of the actor prototypes were not loaded
> 
> failed to initialize exiting

Post the complete console log, I can't help you otherwise.

**Comment by symbios24** [comment]
i did that and now i get an error saying:

some of the actor prototypes were not loaded

failed to initialize exiting

**Comment by pjasicek** [comment]
`C:\Users\pjasi\github\OpenClaw\Build_Release (master -> origin)
λ .\OpenClaw.exe
INFO: Looking for: config.xml
INFO: Expecting config.xml in path: config.xml
INFO: Loaded with:
        Config File: config.xml
        Saves File: SAVES.XML
INFO: >>>>> Initializing display...
INFO: Display successfully initialized.
INFO: >>>>> Initializing audio...
INFO: MIDI RPC Server started. [MidiProc.exe]
INFO: RPC Client successfully initialized
INFO: RPC Server and Client successfully handshaked
INFO: Audio successfully initialized.
INFO: >>>>> Initializing font...
INFO: Font successfully initialized...
INFO: >>>>> Initializing resource cache...
INFO: Resource cache successfully initialized
INFO: >>>>> Loading actor prototypes...
INFO: Actor prototypes loaded successfully.
INFO: "/level_metadata/level1.xml": level metadata file successfully loaded.
INFO: "/level_metadata/level10.xml": level metadata file successfully loaded.
INFO: "/level_metadata/level2.xml": level metadata file successfully loaded.
INFO: "/level_metadata/level3.xml": level metadata file successfully loaded.
INFO: "/level_metadata/level4.xml": level metadata file successfully loaded.
INFO: "/level_metadata/level5.xml": level metadata file successfully loaded.
INFO: "/level_metadata/level6.xml": level metadata file successfully loaded.
INFO: "/level_metadata/level7.xml": level metadata file successfully loaded.
INFO: "/level_metadata/level8.xml": level metadata file successfully loaded.
INFO: "/level_metadata/level9.xml": level metadata file successfully loaded.
INFO: Changing to: 3`

The section above is a complete console log when you run the openclaw binary. Post it here so that I can examine it and see what's wrong.

**Comment by symbios24** [comment]
its big to write it all

ActorPrototype_level111_Mercat was not found
the same error for the files: siren,fish,togglepeg,brakeplank,conveyorbelt
laser,sireprojectile,tridentprojectile
then it goes to level 112
mercat,crumblingpeg,siren,fish,togglepeg,aquatis,rockspring,pathelevator

and then this
some of the actor prototypes were not loaded

failed to initialize exiting

**Comment by pjasicek** [comment]
Create a screenshot or copy-paste it here.

**Comment by symbios24** [comment]
https://ibb.co/GCsrGzX

**Comment by pjasicek** [comment]
hmmm, try to replace the ASSETS.ZIP file with this:

https://github.com/pjasicek/OpenClaw/raw/master/Build_Release/ASSETS.ZIP

If that does not help, checkout some earlier version... but it should work, I think I tested the pull requests.

**Comment by symbios24** [comment]
it worked and upon loading of the first level crashed something about sound-fonts anyway thank you

**Comment by symbios24** [comment]
is it possible to put in the releases a compiled version for raspberry pi ready to work and only to need the res file?

thank you

**Comment by pjasicek** [comment]
I do not have Raspberry Pi nor do I have the toolchain, sorry

**Comment by symbios24** [comment]
what toolchain

**Comment by symbios24** [comment]
https://ibb.co/M2v0tQv

**Comment by pjasicek** [comment]
Toolchain = set of compilation programs used to compile a program for a given PC architecture, Raspberry Pi uses different architecture than usual PCs so it needs its separate toolchain (that is, if I'd want to crosscompile it on my PC)

Check Raspberry Pi memory, if you are not running out. OpenClaw is not really optimised memory-usage wise.

For the SoundFont problem, it's specific to RPi - check https://www.google.com/search?q=couldnt+load+soundfont+file&oq=couldnt+load+soundfont+file&aqs=chrome..69i57j0l5.2728j0j4&sourceid=chrome&ie=UTF-8 search results, some links may contain a way to fix it.

**Comment by symbios24** [comment]
i increased the swapfile size and free as much as memory possible still crashed i give it up thanks

**Comment by Askmewho** [comment]
Hi!! First, this games need the mesa driver to run properly. I never had any memory problem at all. I think you have some trouble with you data files. The game its on early stages of development I believe. Its completable right now??? I will recompile it and re test it if thats the case. But take note than I am running on mesa 19 , so you will need to update to run it properly. The mesa of the default rasobian its 13.5...

**Comment by symbios24** [comment]
thanks how to install mesa?

**Comment by Askmewho** [comment]
Mesa its by default included on your raspbian. You just need to activate it!! Google it .but its a bit outdated. here is an upgrade instruction made by me based on anholt wiki https://drive.google.com/file/d/1gXvu8sMwMGktR2Dsu4pt5Riu6OyMzlMd/view?usp=sharing
