### ISSUE TITLE
Unit tests?

### ISSUE THREAD

**Issue by krzema12** [pjasicek/OpenClaw#28]
Hi guys, I really appreciate your work here. However I noticed that there are no unit tests. Have you considered writing them? Do you have some thoughts about it? I don't have much experience with writing games, so maybe by any reason it's fine not to write them, but generally unit tests are invaluable e.g. as a safety net - they help to prevent regressions.

**Comment by pjasicek** [comment]
I made unit tests as I was developing the libwap library, because there is a really clear interface which is not coupled with the rest of the code. This project is in libwap_tests project folder.

As for the game itself, it is really tricky. There is some engine-startup general testing in BaseGameApp.cpp done, but not nearly enough, just tests that all subsystems were properly initialized. 

Then I am a guy who puts a lot of effort into putting proper asserts to code, there are around 500 asserts, so when something goes awry, I get an assertion fail and I know exactly what caused the issue.

Making unit test for this game engine is certainly possible, but not all subsystems are made via interfaces for my own convinience reasons. Physics can be mocked since it has interface, I can make Audio as an interface, but for the most part to make this unit-test friendly, there would have to be a HUGE amount of refactoring (which is certainly fine, refactoring is generally great) which would eat up a lot of my time.

I will certainly consider it into the future.

**Comment by krzema12** [comment]
Thanks for the reply. Some of my thoughts below, maybe you'll find them useful:

Asserts in the production code is certainly a good thing to make the problem easier to understand once it appears in runtime, but they don't **prevent** the problem to appear, contrary to the unit tests. It's because once you add a feature, it's darn hard to manually check all paths in the code that already exists and bump into a failing assert.

The semi-deterministic behavior in games is IMO not a reason not to write unit tests. Of course, if one looks at the game as a whole and there's just one element that depends on some random() call, the unit tests don't have a chance to be correct since you may have no luck in a given unit test run and even after 10 iterations, random() will return something not desired. One approach may be to mock the mechanism that provides random values, tell it to return 123 to test a particular case and assert on how the logic behaves.

It's clear that it would be hard to refactor the engine as a whole to be testable, but putting the engine aside, how about at least testing the logics of enemies, weapons and other objects that have logic? They seem to be quite separated from the rest, at least they should be. The engine itself is one part, but looking at the number of logics of objects, it could bring some real benefit when reimplementing all the levels. In some sense, during reimplementation of Claw, the scaling happens mainly in writing the logics, not the engine itself, which should be a common part for all levels and be decoupled from them.

Good luck with coding, can't wait to see further results!

**Comment by pjasicek** [comment]
You are right, I can mock just certain things, like creating actors and checking whether they have proper components. I can also simulate some physics things like actors getting hit by explosions, actors dying after falling on death tiles etc.

I will look into this further after finalizing levels 1&2.

Thank you for this suggestion, it will probably go a long way.

**Comment by pjasicek** [comment]
Reminder for me: Revisit this in July and make plans.
